services:
  custom_osrm:
    image: osrm/osrm-backend
    hostname: osrm
    volumes:
      - ./osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 5000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/hanoi.osm.pbf && 
      osrm-partition /data/hanoi.osrm && 
      osrm-customize /data/hanoi.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/hanoi.osrm
      "

networks:
  default:
    driver: bridge